import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/layouts/Footer";
import Navbar from "./components/layouts/Navbar";
import "./imports.css";
import "primereact/resources/themes/lara-light-purple/theme.css";
import "primeicons/primeicons.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Omni embed example",
    description: "Generated by DataPostie",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            const style = document.createElement('style')
                            style.innerHTML = '@layer tailwind-base, primereact, tailwind-utilities;'
                            style.setAttribute('type', 'text/css')
                            document.querySelector('head').prepend(style)
                        `,
                    }}
                />
            </head>
            <body
                className={`${inter.className} antialiased min-h-screen flex flex-col`}
            >
                <Navbar />
                <main className="grow px-4 py-4">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
